import { Redis } from "@upstash/redis";

const redis = new Redis({
  url: process.env.UPSTASH_REDIS_REST_URL,
  token: process.env.UPSTASH_REDIS_REST_TOKEN,
});

const getUSDtoMXN = async () => {
  try {
    const res = await fetch("https://api.exchangerate-api.com/v4/latest/USD");
    const data = await res.json();
    return data.rates?.MXN || 17.5;
  } catch { return 17.5; }
};

const convertirSalario = (salario, tc) => {
  if (!salario || salario === "Ver en plataforma" || salario === "Por proyecto") return salario;
  const hrMatch = salario.match(/\$([0-9,]+)-([0-9,]+)\/hr/);
  if (hrMatch) {
    const min = Math.round(parseFloat(hrMatch[1].replace(",", "")) * 160 * tc / 1000) * 1000;
    const max = Math.round(parseFloat(hrMatch[2].replace(",", "")) * 160 * tc / 1000) * 1000;
    return `$${min.toLocaleString("es-MX")} - $${max.toLocaleString("es-MX")} MXN/mes`;
  }
  const yrMatch = salario.match(/\$([0-9,]+)-([0-9,]+)\/año/);
  if (yrMatch) {
    const min = Math.round(parseFloat(yrMatch[1].replace(",", "")) * tc / 12 / 1000) * 1000;
    const max = Math.round(parseFloat(yrMatch[2].replace(",", "")) * tc / 12 / 1000) * 1000;
    return `$${min.toLocaleString("es-MX")} - $${max.toLocaleString("es-MX")} MXN/mes`;
  }
  return salario;
};

const PRESENCIALES = [
  { id: "p1000", tipo: "paralegal", modalidad: "presencial", titulo: "Paralegal / Legal · Google Jobs", empresa: "Google Jobs", plataforma: "Google Jobs", ubicacion: "Presencial · Zona Oriente CDMX / EDOMEX", descripcion: "Búsqueda en Google Jobs para Paralegal / Legal. Al abrir filtra por distancia y fecha de publicación.", url: "https://www.google.com/search?q=paralegal%20bilingue&ibp=htl;jobs&htichips=date_posted:week", salario: "Ver en plataforma" },
  { id: "p1001", tipo: "asistente", modalidad: "presencial", titulo: "Asistente Bilingüe · Google Jobs", empresa: "Google Jobs", plataforma: "Google Jobs", ubicacion: "Presencial · Zona Oriente CDMX / EDOMEX", descripcion: "Búsqueda en Google Jobs para Asistente Bilingüe. Al abrir filtra por distancia y fecha de publicación.", url: "https://www.google.com/search?q=asistente%20bilingue&ibp=htl;jobs&htichips=date_posted:week", salario: "Ver en plataforma" },
  { id: "p1002", tipo: "teacher", modalidad: "presencial", titulo: "English Teacher · Google Jobs", empresa: "Google Jobs", plataforma: "Google Jobs", ubicacion: "Presencial · Zona Oriente CDMX / EDOMEX", descripcion: "Búsqueda en Google Jobs para English Teacher. Al abrir filtra por distancia y fecha de publicación.", url: "https://www.google.com/search?q=maestra%20ingles&ibp=htl;jobs&htichips=date_posted:week", salario: "Ver en plataforma" },
  { id: "p1003", tipo: "interprete", modalidad: "presencial", titulo: "Intérprete / Traductora · Google Jobs", empresa: "Google Jobs", plataforma: "Google Jobs", ubicacion: "Presencial · Zona Oriente CDMX / EDOMEX", descripcion: "Búsqueda en Google Jobs para Intérprete / Traductora. Al abrir filtra por distancia y fecha de publicación.", url: "https://www.google.com/search?q=interprete%20bilingue&ibp=htl;jobs&htichips=date_posted:week", salario: "Ver en plataforma" },
  { id: "p1004", tipo: "atencion", modalidad: "presencial", titulo: "Atención Clientes · Google Jobs", empresa: "Google Jobs", plataforma: "Google Jobs", ubicacion: "Presencial · Zona Oriente CDMX / EDOMEX", descripcion: "Búsqueda en Google Jobs para Atención Clientes. Al abrir filtra por distancia y fecha de publicación.", url: "https://www.google.com/search?q=ejecutivo%20bilingue&ibp=htl;jobs&htichips=date_posted:week", salario: "Ver en plataforma" },
  { id: "p1005", tipo: "paralegal", modalidad: "presencial", titulo: "Paralegal / Legal · Iztapalapa · Indeed", empresa: "Indeed", plataforma: "Indeed", ubicacion: "Presencial · Iztapalapa, CDMX", descripcion: "Indeed con ubicación en Iztapalapa. Ordena por fecha para ver las más recientes. Verifica ubicación antes de postularte.", url: "https://www.indeed.com/jobs?q=paralegal%20bilingue&l=Iztapalapa&sort=date", salario: "Ver en plataforma" },
  { id: "p1006", tipo: "paralegal", modalidad: "presencial", titulo: "Paralegal / Legal · Iztapalapa · OCC", empresa: "OCC Mundial", plataforma: "OCC", ubicacion: "Presencial · Iztapalapa, CDMX", descripcion: "OCC con ubicación en Iztapalapa. Confirma que la ubicación sea correcta antes de aplicar.", url: "https://www.occ.com.mx/empleos/de-paralegal/?location=Iztapalapa", salario: "Ver en plataforma" },
  { id: "p1007", tipo: "paralegal", modalidad: "presencial", titulo: "Paralegal / Legal · Iztapalapa · Computrabajo", empresa: "Computrabajo", plataforma: "Computrabajo", ubicacion: "Presencial · Iztapalapa, CDMX", descripcion: "Computrabajo con ubicación en Iztapalapa. Verifica ubicación exacta antes de postularte.", url: "https://mx.computrabajo.com/trabajo-de-paralegal-bilingue?l=Iztapalapa", salario: "Ver en plataforma" },
  { id: "p1008", tipo: "paralegal", modalidad: "presencial", titulo: "Paralegal / Legal · Iztapalapa · LinkedIn", empresa: "LinkedIn", plataforma: "LinkedIn", ubicacion: "Presencial · Iztapalapa, CDMX", descripcion: "LinkedIn con ubicación en Iztapalapa, publicadas esta semana. Verifica ubicación antes de postularte.", url: "https://www.linkedin.com/jobs/search/?keywords=paralegal%20bilingual&location=Iztapalapa%2C%20Mexico&f_TPR=r604800", salario: "Ver en plataforma" },
  { id: "p1009", tipo: "paralegal", modalidad: "presencial", titulo: "Paralegal / Legal · Nezahualcóyotl · Indeed", empresa: "Indeed", plataforma: "Indeed", ubicacion: "Presencial · Nezahualcóyotl, EDOMEX", descripcion: "Indeed con ubicación en Nezahualcóyotl. Ordena por fecha para ver las más recientes. Verifica ubicación antes de postularte.", url: "https://www.indeed.com/jobs?q=paralegal%20bilingue&l=Nezahualc%C3%B3yotl&sort=date", salario: "Ver en plataforma" },
  { id: "p1010", tipo: "paralegal", modalidad: "presencial", titulo: "Paralegal / Legal · Nezahualcóyotl · OCC", empresa: "OCC Mundial", plataforma: "OCC", ubicacion: "Presencial · Nezahualcóyotl, EDOMEX", descripcion: "OCC con ubicación en Nezahualcóyotl. Confirma que la ubicación sea correcta antes de aplicar.", url: "https://www.occ.com.mx/empleos/de-paralegal/?location=Nezahualc%C3%B3yotl", salario: "Ver en plataforma" },
  { id: "p1011", tipo: "paralegal", modalidad: "presencial", titulo: "Paralegal / Legal · Nezahualcóyotl · Computrabajo", empresa: "Computrabajo", plataforma: "Computrabajo", ubicacion: "Presencial · Nezahualcóyotl, EDOMEX", descripcion: "Computrabajo con ubicación en Nezahualcóyotl. Verifica ubicación exacta antes de postularte.", url: "https://mx.computrabajo.com/trabajo-de-paralegal-bilingue?l=Nezahualc%C3%B3yotl", salario: "Ver en plataforma" },
  { id: "p1012", tipo: "paralegal", modalidad: "presencial", titulo: "Paralegal / Legal · Nezahualcóyotl · LinkedIn", empresa: "LinkedIn", plataforma: "LinkedIn", ubicacion: "Presencial · Nezahualcóyotl, EDOMEX", descripcion: "LinkedIn con ubicación en Nezahualcóyotl, publicadas esta semana. Verifica ubicación antes de postularte.", url: "https://www.linkedin.com/jobs/search/?keywords=paralegal%20bilingual&location=Nezahualc%C3%B3yotl%2C%20Mexico&f_TPR=r604800", salario: "Ver en plataforma" },
  { id: "p1013", tipo: "paralegal", modalidad: "presencial", titulo: "Paralegal / Legal · Los Reyes La Paz · Indeed", empresa: "Indeed", plataforma: "Indeed", ubicacion: "Presencial · Los Reyes La Paz, EDOMEX", descripcion: "Indeed con ubicación en Los Reyes La Paz. Ordena por fecha para ver las más recientes. Verifica ubicación antes de postularte.", url: "https://www.indeed.com/jobs?q=paralegal%20bilingue&l=Los%20Reyes%20La%20Paz&sort=date", salario: "Ver en plataforma" },
  { id: "p1014", tipo: "paralegal", modalidad: "presencial", titulo: "Paralegal / Legal · Los Reyes La Paz · OCC", empresa: "OCC Mundial", plataforma: "OCC", ubicacion: "Presencial · Los Reyes La Paz, EDOMEX", descripcion: "OCC con ubicación en Los Reyes La Paz. Confirma que la ubicación sea correcta antes de aplicar.", url: "https://www.occ.com.mx/empleos/de-paralegal/?location=Los%20Reyes%20La%20Paz", salario: "Ver en plataforma" },
  { id: "p1015", tipo: "paralegal", modalidad: "presencial", titulo: "Paralegal / Legal · Los Reyes La Paz · Computrabajo", empresa: "Computrabajo", plataforma: "Computrabajo", ubicacion: "Presencial · Los Reyes La Paz, EDOMEX", descripcion: "Computrabajo con ubicación en Los Reyes La Paz. Verifica ubicación exacta antes de postularte.", url: "https://mx.computrabajo.com/trabajo-de-paralegal-bilingue?l=Los%20Reyes%20La%20Paz", salario: "Ver en plataforma" },
  { id: "p1016", tipo: "paralegal", modalidad: "presencial", titulo: "Paralegal / Legal · Los Reyes La Paz · LinkedIn", empresa: "LinkedIn", plataforma: "LinkedIn", ubicacion: "Presencial · Los Reyes La Paz, EDOMEX", descripcion: "LinkedIn con ubicación en Los Reyes La Paz, publicadas esta semana. Verifica ubicación antes de postularte.", url: "https://www.linkedin.com/jobs/search/?keywords=paralegal%20bilingual&location=Los%20Reyes%20La%20Paz%2C%20Mexico&f_TPR=r604800", salario: "Ver en plataforma" },
  { id: "p1017", tipo: "paralegal", modalidad: "presencial", titulo: "Paralegal / Legal · Texcoco · Indeed", empresa: "Indeed", plataforma: "Indeed", ubicacion: "Presencial · Texcoco, EDOMEX", descripcion: "Indeed con ubicación en Texcoco. Ordena por fecha para ver las más recientes. Verifica ubicación antes de postularte.", url: "https://www.indeed.com/jobs?q=paralegal%20bilingue&l=Texcoco&sort=date", salario: "Ver en plataforma" },
  { id: "p1018", tipo: "paralegal", modalidad: "presencial", titulo: "Paralegal / Legal · Texcoco · OCC", empresa: "OCC Mundial", plataforma: "OCC", ubicacion: "Presencial · Texcoco, EDOMEX", descripcion: "OCC con ubicación en Texcoco. Confirma que la ubicación sea correcta antes de aplicar.", url: "https://www.occ.com.mx/empleos/de-paralegal/?location=Texcoco", salario: "Ver en plataforma" },
  { id: "p1019", tipo: "paralegal", modalidad: "presencial", titulo: "Paralegal / Legal · Texcoco · Computrabajo", empresa: "Computrabajo", plataforma: "Computrabajo", ubicacion: "Presencial · Texcoco, EDOMEX", descripcion: "Computrabajo con ubicación en Texcoco. Verifica ubicación exacta antes de postularte.", url: "https://mx.computrabajo.com/trabajo-de-paralegal-bilingue?l=Texcoco", salario: "Ver en plataforma" },
  { id: "p1020", tipo: "paralegal", modalidad: "presencial", titulo: "Paralegal / Legal · Texcoco · LinkedIn", empresa: "LinkedIn", plataforma: "LinkedIn", ubicacion: "Presencial · Texcoco, EDOMEX", descripcion: "LinkedIn con ubicación en Texcoco, publicadas esta semana. Verifica ubicación antes de postularte.", url: "https://www.linkedin.com/jobs/search/?keywords=paralegal%20bilingual&location=Texcoco%2C%20Mexico&f_TPR=r604800", salario: "Ver en plataforma" },
  { id: "p1021", tipo: "paralegal", modalidad: "presencial", titulo: "Paralegal / Legal · Chimalhuacán · Indeed", empresa: "Indeed", plataforma: "Indeed", ubicacion: "Presencial · Chimalhuacán, EDOMEX", descripcion: "Indeed con ubicación en Chimalhuacán. Ordena por fecha para ver las más recientes. Verifica ubicación antes de postularte.", url: "https://www.indeed.com/jobs?q=paralegal%20bilingue&l=Chimalhuac%C3%A1n&sort=date", salario: "Ver en plataforma" },
  { id: "p1022", tipo: "paralegal", modalidad: "presencial", titulo: "Paralegal / Legal · Chimalhuacán · OCC", empresa: "OCC Mundial", plataforma: "OCC", ubicacion: "Presencial · Chimalhuacán, EDOMEX", descripcion: "OCC con ubicación en Chimalhuacán. Confirma que la ubicación sea correcta antes de aplicar.", url: "https://www.occ.com.mx/empleos/de-paralegal/?location=Chimalhuac%C3%A1n", salario: "Ver en plataforma" },
  { id: "p1023", tipo: "paralegal", modalidad: "presencial", titulo: "Paralegal / Legal · Chimalhuacán · Computrabajo", empresa: "Computrabajo", plataforma: "Computrabajo", ubicacion: "Presencial · Chimalhuacán, EDOMEX", descripcion: "Computrabajo con ubicación en Chimalhuacán. Verifica ubicación exacta antes de postularte.", url: "https://mx.computrabajo.com/trabajo-de-paralegal-bilingue?l=Chimalhuac%C3%A1n", salario: "Ver en plataforma" },
  { id: "p1024", tipo: "paralegal", modalidad: "presencial", titulo: "Paralegal / Legal · Chimalhuacán · LinkedIn", empresa: "LinkedIn", plataforma: "LinkedIn", ubicacion: "Presencial · Chimalhuacán, EDOMEX", descripcion: "LinkedIn con ubicación en Chimalhuacán, publicadas esta semana. Verifica ubicación antes de postularte.", url: "https://www.linkedin.com/jobs/search/?keywords=paralegal%20bilingual&location=Chimalhuac%C3%A1n%2C%20Mexico&f_TPR=r604800", salario: "Ver en plataforma" },
  { id: "p1025", tipo: "asistente", modalidad: "presencial", titulo: "Asistente Bilingüe · Iztapalapa · Indeed", empresa: "Indeed", plataforma: "Indeed", ubicacion: "Presencial · Iztapalapa, CDMX", descripcion: "Indeed con ubicación en Iztapalapa. Ordena por fecha para ver las más recientes. Verifica ubicación antes de postularte.", url: "https://www.indeed.com/jobs?q=asistente%20bilingue%20ingles&l=Iztapalapa&sort=date", salario: "Ver en plataforma" },
  { id: "p1026", tipo: "asistente", modalidad: "presencial", titulo: "Asistente Bilingüe · Iztapalapa · OCC", empresa: "OCC Mundial", plataforma: "OCC", ubicacion: "Presencial · Iztapalapa, CDMX", descripcion: "OCC con ubicación en Iztapalapa. Confirma que la ubicación sea correcta antes de aplicar.", url: "https://www.occ.com.mx/empleos/de-asistente-bilingue/?location=Iztapalapa", salario: "Ver en plataforma" },
  { id: "p1027", tipo: "asistente", modalidad: "presencial", titulo: "Asistente Bilingüe · Iztapalapa · Computrabajo", empresa: "Computrabajo", plataforma: "Computrabajo", ubicacion: "Presencial · Iztapalapa, CDMX", descripcion: "Computrabajo con ubicación en Iztapalapa. Verifica ubicación exacta antes de postularte.", url: "https://mx.computrabajo.com/trabajo-de-asistente-bilingue?l=Iztapalapa", salario: "Ver en plataforma" },
  { id: "p1028", tipo: "asistente", modalidad: "presencial", titulo: "Asistente Bilingüe · Iztapalapa · LinkedIn", empresa: "LinkedIn", plataforma: "LinkedIn", ubicacion: "Presencial · Iztapalapa, CDMX", descripcion: "LinkedIn con ubicación en Iztapalapa, publicadas esta semana. Verifica ubicación antes de postularte.", url: "https://www.linkedin.com/jobs/search/?keywords=asistente%20bilingual&location=Iztapalapa%2C%20Mexico&f_TPR=r604800", salario: "Ver en plataforma" },
  { id: "p1029", tipo: "asistente", modalidad: "presencial", titulo: "Asistente Bilingüe · Nezahualcóyotl · Indeed", empresa: "Indeed", plataforma: "Indeed", ubicacion: "Presencial · Nezahualcóyotl, EDOMEX", descripcion: "Indeed con ubicación en Nezahualcóyotl. Ordena por fecha para ver las más recientes. Verifica ubicación antes de postularte.", url: "https://www.indeed.com/jobs?q=asistente%20bilingue%20ingles&l=Nezahualc%C3%B3yotl&sort=date", salario: "Ver en plataforma" },
  { id: "p1030", tipo: "asistente", modalidad: "presencial", titulo: "Asistente Bilingüe · Nezahualcóyotl · OCC", empresa: "OCC Mundial", plataforma: "OCC", ubicacion: "Presencial · Nezahualcóyotl, EDOMEX", descripcion: "OCC con ubicación en Nezahualcóyotl. Confirma que la ubicación sea correcta antes de aplicar.", url: "https://www.occ.com.mx/empleos/de-asistente-bilingue/?location=Nezahualc%C3%B3yotl", salario: "Ver en plataforma" },
  { id: "p1031", tipo: "asistente", modalidad: "presencial", titulo: "Asistente Bilingüe · Nezahualcóyotl · Computrabajo", empresa: "Computrabajo", plataforma: "Computrabajo", ubicacion: "Presencial · Nezahualcóyotl, EDOMEX", descripcion: "Computrabajo con ubicación en Nezahualcóyotl. Verifica ubicación exacta antes de postularte.", url: "https://mx.computrabajo.com/trabajo-de-asistente-bilingue?l=Nezahualc%C3%B3yotl", salario: "Ver en plataforma" },
  { id: "p1032", tipo: "asistente", modalidad: "presencial", titulo: "Asistente Bilingüe · Nezahualcóyotl · LinkedIn", empresa: "LinkedIn", plataforma: "LinkedIn", ubicacion: "Presencial · Nezahualcóyotl, EDOMEX", descripcion: "LinkedIn con ubicación en Nezahualcóyotl, publicadas esta semana. Verifica ubicación antes de postularte.", url: "https://www.linkedin.com/jobs/search/?keywords=asistente%20bilingual&location=Nezahualc%C3%B3yotl%2C%20Mexico&f_TPR=r604800", salario: "Ver en plataforma" },
  { id: "p1033", tipo: "asistente", modalidad: "presencial", titulo: "Asistente Bilingüe · Los Reyes La Paz · Indeed", empresa: "Indeed", plataforma: "Indeed", ubicacion: "Presencial · Los Reyes La Paz, EDOMEX", descripcion: "Indeed con ubicación en Los Reyes La Paz. Ordena por fecha para ver las más recientes. Verifica ubicación antes de postularte.", url: "https://www.indeed.com/jobs?q=asistente%20bilingue%20ingles&l=Los%20Reyes%20La%20Paz&sort=date", salario: "Ver en plataforma" },
  { id: "p1034", tipo: "asistente", modalidad: "presencial", titulo: "Asistente Bilingüe · Los Reyes La Paz · OCC", empresa: "OCC Mundial", plataforma: "OCC", ubicacion: "Presencial · Los Reyes La Paz, EDOMEX", descripcion: "OCC con ubicación en Los Reyes La Paz. Confirma que la ubicación sea correcta antes de aplicar.", url: "https://www.occ.com.mx/empleos/de-asistente-bilingue/?location=Los%20Reyes%20La%20Paz", salario: "Ver en plataforma" },
  { id: "p1035", tipo: "asistente", modalidad: "presencial", titulo: "Asistente Bilingüe · Los Reyes La Paz · Computrabajo", empresa: "Computrabajo", plataforma: "Computrabajo", ubicacion: "Presencial · Los Reyes La Paz, EDOMEX", descripcion: "Computrabajo con ubicación en Los Reyes La Paz. Verifica ubicación exacta antes de postularte.", url: "https://mx.computrabajo.com/trabajo-de-asistente-bilingue?l=Los%20Reyes%20La%20Paz", salario: "Ver en plataforma" },
  { id: "p1036", tipo: "asistente", modalidad: "presencial", titulo: "Asistente Bilingüe · Los Reyes La Paz · LinkedIn", empresa: "LinkedIn", plataforma: "LinkedIn", ubicacion: "Presencial · Los Reyes La Paz, EDOMEX", descripcion: "LinkedIn con ubicación en Los Reyes La Paz, publicadas esta semana. Verifica ubicación antes de postularte.", url: "https://www.linkedin.com/jobs/search/?keywords=asistente%20bilingual&location=Los%20Reyes%20La%20Paz%2C%20Mexico&f_TPR=r604800", salario: "Ver en plataforma" },
  { id: "p1037", tipo: "asistente", modalidad: "presencial", titulo: "Asistente Bilingüe · Texcoco · Indeed", empresa: "Indeed", plataforma: "Indeed", ubicacion: "Presencial · Texcoco, EDOMEX", descripcion: "Indeed con ubicación en Texcoco. Ordena por fecha para ver las más recientes. Verifica ubicación antes de postularte.", url: "https://www.indeed.com/jobs?q=asistente%20bilingue%20ingles&l=Texcoco&sort=date", salario: "Ver en plataforma" },
  { id: "p1038", tipo: "asistente", modalidad: "presencial", titulo: "Asistente Bilingüe · Texcoco · OCC", empresa: "OCC Mundial", plataforma: "OCC", ubicacion: "Presencial · Texcoco, EDOMEX", descripcion: "OCC con ubicación en Texcoco. Confirma que la ubicación sea correcta antes de aplicar.", url: "https://www.occ.com.mx/empleos/de-asistente-bilingue/?location=Texcoco", salario: "Ver en plataforma" },
  { id: "p1039", tipo: "asistente", modalidad: "presencial", titulo: "Asistente Bilingüe · Texcoco · Computrabajo", empresa: "Computrabajo", plataforma: "Computrabajo", ubicacion: "Presencial · Texcoco, EDOMEX", descripcion: "Computrabajo con ubicación en Texcoco. Verifica ubicación exacta antes de postularte.", url: "https://mx.computrabajo.com/trabajo-de-asistente-bilingue?l=Texcoco", salario: "Ver en plataforma" },
  { id: "p1040", tipo: "asistente", modalidad: "presencial", titulo: "Asistente Bilingüe · Texcoco · LinkedIn", empresa: "LinkedIn", plataforma: "LinkedIn", ubicacion: "Presencial · Texcoco, EDOMEX", descripcion: "LinkedIn con ubicación en Texcoco, publicadas esta semana. Verifica ubicación antes de postularte.", url: "https://www.linkedin.com/jobs/search/?keywords=asistente%20bilingual&location=Texcoco%2C%20Mexico&f_TPR=r604800", salario: "Ver en plataforma" },
  { id: "p1041", tipo: "asistente", modalidad: "presencial", titulo: "Asistente Bilingüe · Chimalhuacán · Indeed", empresa: "Indeed", plataforma: "Indeed", ubicacion: "Presencial · Chimalhuacán, EDOMEX", descripcion: "Indeed con ubicación en Chimalhuacán. Ordena por fecha para ver las más recientes. Verifica ubicación antes de postularte.", url: "https://www.indeed.com/jobs?q=asistente%20bilingue%20ingles&l=Chimalhuac%C3%A1n&sort=date", salario: "Ver en plataforma" },
  { id: "p1042", tipo: "asistente", modalidad: "presencial", titulo: "Asistente Bilingüe · Chimalhuacán · OCC", empresa: "OCC Mundial", plataforma: "OCC", ubicacion: "Presencial · Chimalhuacán, EDOMEX", descripcion: "OCC con ubicación en Chimalhuacán. Confirma que la ubicación sea correcta antes de aplicar.", url: "https://www.occ.com.mx/empleos/de-asistente-bilingue/?location=Chimalhuac%C3%A1n", salario: "Ver en plataforma" },
  { id: "p1043", tipo: "asistente", modalidad: "presencial", titulo: "Asistente Bilingüe · Chimalhuacán · Computrabajo", empresa: "Computrabajo", plataforma: "Computrabajo", ubicacion: "Presencial · Chimalhuacán, EDOMEX", descripcion: "Computrabajo con ubicación en Chimalhuacán. Verifica ubicación exacta antes de postularte.", url: "https://mx.computrabajo.com/trabajo-de-asistente-bilingue?l=Chimalhuac%C3%A1n", salario: "Ver en plataforma" },
  { id: "p1044", tipo: "asistente", modalidad: "presencial", titulo: "Asistente Bilingüe · Chimalhuacán · LinkedIn", empresa: "LinkedIn", plataforma: "LinkedIn", ubicacion: "Presencial · Chimalhuacán, EDOMEX", descripcion: "LinkedIn con ubicación en Chimalhuacán, publicadas esta semana. Verifica ubicación antes de postularte.", url: "https://www.linkedin.com/jobs/search/?keywords=asistente%20bilingual&location=Chimalhuac%C3%A1n%2C%20Mexico&f_TPR=r604800", salario: "Ver en plataforma" },
  { id: "p1045", tipo: "teacher", modalidad: "presencial", titulo: "English Teacher · Iztapalapa · Indeed", empresa: "Indeed", plataforma: "Indeed", ubicacion: "Presencial · Iztapalapa, CDMX", descripcion: "Indeed con ubicación en Iztapalapa. Ordena por fecha para ver las más recientes. Verifica ubicación antes de postularte.", url: "https://www.indeed.com/jobs?q=maestra%20ingles&l=Iztapalapa&sort=date", salario: "Ver en plataforma" },
  { id: "p1046", tipo: "teacher", modalidad: "presencial", titulo: "English Teacher · Iztapalapa · OCC", empresa: "OCC Mundial", plataforma: "OCC", ubicacion: "Presencial · Iztapalapa, CDMX", descripcion: "OCC con ubicación en Iztapalapa. Confirma que la ubicación sea correcta antes de aplicar.", url: "https://www.occ.com.mx/empleos/de-maestro-ingles/?location=Iztapalapa", salario: "Ver en plataforma" },
  { id: "p1047", tipo: "teacher", modalidad: "presencial", titulo: "English Teacher · Iztapalapa · Computrabajo", empresa: "Computrabajo", plataforma: "Computrabajo", ubicacion: "Presencial · Iztapalapa, CDMX", descripcion: "Computrabajo con ubicación en Iztapalapa. Verifica ubicación exacta antes de postularte.", url: "https://mx.computrabajo.com/trabajo-de-instructor-ingles?l=Iztapalapa", salario: "Ver en plataforma" },
  { id: "p1048", tipo: "teacher", modalidad: "presencial", titulo: "English Teacher · Iztapalapa · LinkedIn", empresa: "LinkedIn", plataforma: "LinkedIn", ubicacion: "Presencial · Iztapalapa, CDMX", descripcion: "LinkedIn con ubicación en Iztapalapa, publicadas esta semana. Verifica ubicación antes de postularte.", url: "https://www.linkedin.com/jobs/search/?keywords=english%20teacher&location=Iztapalapa%2C%20Mexico&f_TPR=r604800", salario: "Ver en plataforma" },
  { id: "p1049", tipo: "teacher", modalidad: "presencial", titulo: "English Teacher · Nezahualcóyotl · Indeed", empresa: "Indeed", plataforma: "Indeed", ubicacion: "Presencial · Nezahualcóyotl, EDOMEX", descripcion: "Indeed con ubicación en Nezahualcóyotl. Ordena por fecha para ver las más recientes. Verifica ubicación antes de postularte.", url: "https://www.indeed.com/jobs?q=maestra%20ingles&l=Nezahualc%C3%B3yotl&sort=date", salario: "Ver en plataforma" },
  { id: "p1050", tipo: "teacher", modalidad: "presencial", titulo: "English Teacher · Nezahualcóyotl · OCC", empresa: "OCC Mundial", plataforma: "OCC", ubicacion: "Presencial · Nezahualcóyotl, EDOMEX", descripcion: "OCC con ubicación en Nezahualcóyotl. Confirma que la ubicación sea correcta antes de aplicar.", url: "https://www.occ.com.mx/empleos/de-maestro-ingles/?location=Nezahualc%C3%B3yotl", salario: "Ver en plataforma" },
  { id: "p1051", tipo: "teacher", modalidad: "presencial", titulo: "English Teacher · Nezahualcóyotl · Computrabajo", empresa: "Computrabajo", plataforma: "Computrabajo", ubicacion: "Presencial · Nezahualcóyotl, EDOMEX", descripcion: "Computrabajo con ubicación en Nezahualcóyotl. Verifica ubicación exacta antes de postularte.", url: "https://mx.computrabajo.com/trabajo-de-instructor-ingles?l=Nezahualc%C3%B3yotl", salario: "Ver en plataforma" },
  { id: "p1052", tipo: "teacher", modalidad: "presencial", titulo: "English Teacher · Nezahualcóyotl · LinkedIn", empresa: "LinkedIn", plataforma: "LinkedIn", ubicacion: "Presencial · Nezahualcóyotl, EDOMEX", descripcion: "LinkedIn con ubicación en Nezahualcóyotl, publicadas esta semana. Verifica ubicación antes de postularte.", url: "https://www.linkedin.com/jobs/search/?keywords=english%20teacher&location=Nezahualc%C3%B3yotl%2C%20Mexico&f_TPR=r604800", salario: "Ver en plataforma" },
  { id: "p1053", tipo: "teacher", modalidad: "presencial", titulo: "English Teacher · Los Reyes La Paz · Indeed", empresa: "Indeed", plataforma: "Indeed", ubicacion: "Presencial · Los Reyes La Paz, EDOMEX", descripcion: "Indeed con ubicación en Los Reyes La Paz. Ordena por fecha para ver las más recientes. Verifica ubicación antes de postularte.", url: "https://www.indeed.com/jobs?q=maestra%20ingles&l=Los%20Reyes%20La%20Paz&sort=date", salario: "Ver en plataforma" },
  { id: "p1054", tipo: "teacher", modalidad: "presencial", titulo: "English Teacher · Los Reyes La Paz · OCC", empresa: "OCC Mundial", plataforma: "OCC", ubicacion: "Presencial · Los Reyes La Paz, EDOMEX", descripcion: "OCC con ubicación en Los Reyes La Paz. Confirma que la ubicación sea correcta antes de aplicar.", url: "https://www.occ.com.mx/empleos/de-maestro-ingles/?location=Los%20Reyes%20La%20Paz", salario: "Ver en plataforma" },
  { id: "p1055", tipo: "teacher", modalidad: "presencial", titulo: "English Teacher · Los Reyes La Paz · Computrabajo", empresa: "Computrabajo", plataforma: "Computrabajo", ubicacion: "Presencial · Los Reyes La Paz, EDOMEX", descripcion: "Computrabajo con ubicación en Los Reyes La Paz. Verifica ubicación exacta antes de postularte.", url: "https://mx.computrabajo.com/trabajo-de-instructor-ingles?l=Los%20Reyes%20La%20Paz", salario: "Ver en plataforma" },
  { id: "p1056", tipo: "teacher", modalidad: "presencial", titulo: "English Teacher · Los Reyes La Paz · LinkedIn", empresa: "LinkedIn", plataforma: "LinkedIn", ubicacion: "Presencial · Los Reyes La Paz, EDOMEX", descripcion: "LinkedIn con ubicación en Los Reyes La Paz, publicadas esta semana. Verifica ubicación antes de postularte.", url: "https://www.linkedin.com/jobs/search/?keywords=english%20teacher&location=Los%20Reyes%20La%20Paz%2C%20Mexico&f_TPR=r604800", salario: "Ver en plataforma" },
  { id: "p1057", tipo: "teacher", modalidad: "presencial", titulo: "English Teacher · Texcoco · Indeed", empresa: "Indeed", plataforma: "Indeed", ubicacion: "Presencial · Texcoco, EDOMEX", descripcion: "Indeed con ubicación en Texcoco. Ordena por fecha para ver las más recientes. Verifica ubicación antes de postularte.", url: "https://www.indeed.com/jobs?q=maestra%20ingles&l=Texcoco&sort=date", salario: "Ver en plataforma" },
  { id: "p1058", tipo: "teacher", modalidad: "presencial", titulo: "English Teacher · Texcoco · OCC", empresa: "OCC Mundial", plataforma: "OCC", ubicacion: "Presencial · Texcoco, EDOMEX", descripcion: "OCC con ubicación en Texcoco. Confirma que la ubicación sea correcta antes de aplicar.", url: "https://www.occ.com.mx/empleos/de-maestro-ingles/?location=Texcoco", salario: "Ver en plataforma" },
  { id: "p1059", tipo: "teacher", modalidad: "presencial", titulo: "English Teacher · Texcoco · Computrabajo", empresa: "Computrabajo", plataforma: "Computrabajo", ubicacion: "Presencial · Texcoco, EDOMEX", descripcion: "Computrabajo con ubicación en Texcoco. Verifica ubicación exacta antes de postularte.", url: "https://mx.computrabajo.com/trabajo-de-instructor-ingles?l=Texcoco", salario: "Ver en plataforma" },
  { id: "p1060", tipo: "teacher", modalidad: "presencial", titulo: "English Teacher · Texcoco · LinkedIn", empresa: "LinkedIn", plataforma: "LinkedIn", ubicacion: "Presencial · Texcoco, EDOMEX", descripcion: "LinkedIn con ubicación en Texcoco, publicadas esta semana. Verifica ubicación antes de postularte.", url: "https://www.linkedin.com/jobs/search/?keywords=english%20teacher&location=Texcoco%2C%20Mexico&f_TPR=r604800", salario: "Ver en plataforma" },
  { id: "p1061", tipo: "teacher", modalidad: "presencial", titulo: "English Teacher · Chimalhuacán · Indeed", empresa: "Indeed", plataforma: "Indeed", ubicacion: "Presencial · Chimalhuacán, EDOMEX", descripcion: "Indeed con ubicación en Chimalhuacán. Ordena por fecha para ver las más recientes. Verifica ubicación antes de postularte.", url: "https://www.indeed.com/jobs?q=maestra%20ingles&l=Chimalhuac%C3%A1n&sort=date", salario: "Ver en plataforma" },
  { id: "p1062", tipo: "teacher", modalidad: "presencial", titulo: "English Teacher · Chimalhuacán · OCC", empresa: "OCC Mundial", plataforma: "OCC", ubicacion: "Presencial · Chimalhuacán, EDOMEX", descripcion: "OCC con ubicación en Chimalhuacán. Confirma que la ubicación sea correcta antes de aplicar.", url: "https://www.occ.com.mx/empleos/de-maestro-ingles/?location=Chimalhuac%C3%A1n", salario: "Ver en plataforma" },
  { id: "p1063", tipo: "teacher", modalidad: "presencial", titulo: "English Teacher · Chimalhuacán · Computrabajo", empresa: "Computrabajo", plataforma: "Computrabajo", ubicacion: "Presencial · Chimalhuacán, EDOMEX", descripcion: "Computrabajo con ubicación en Chimalhuacán. Verifica ubicación exacta antes de postularte.", url: "https://mx.computrabajo.com/trabajo-de-instructor-ingles?l=Chimalhuac%C3%A1n", salario: "Ver en plataforma" },
  { id: "p1064", tipo: "teacher", modalidad: "presencial", titulo: "English Teacher · Chimalhuacán · LinkedIn", empresa: "LinkedIn", plataforma: "LinkedIn", ubicacion: "Presencial · Chimalhuacán, EDOMEX", descripcion: "LinkedIn con ubicación en Chimalhuacán, publicadas esta semana. Verifica ubicación antes de postularte.", url: "https://www.linkedin.com/jobs/search/?keywords=english%20teacher&location=Chimalhuac%C3%A1n%2C%20Mexico&f_TPR=r604800", salario: "Ver en plataforma" },
  { id: "p1065", tipo: "interprete", modalidad: "presencial", titulo: "Intérprete / Traductora · Iztapalapa · Indeed", empresa: "Indeed", plataforma: "Indeed", ubicacion: "Presencial · Iztapalapa, CDMX", descripcion: "Indeed con ubicación en Iztapalapa. Ordena por fecha para ver las más recientes. Verifica ubicación antes de postularte.", url: "https://www.indeed.com/jobs?q=interprete%20bilingue&l=Iztapalapa&sort=date", salario: "Ver en plataforma" },
  { id: "p1066", tipo: "interprete", modalidad: "presencial", titulo: "Intérprete / Traductora · Iztapalapa · OCC", empresa: "OCC Mundial", plataforma: "OCC", ubicacion: "Presencial · Iztapalapa, CDMX", descripcion: "OCC con ubicación en Iztapalapa. Confirma que la ubicación sea correcta antes de aplicar.", url: "https://www.occ.com.mx/empleos/de-interprete-bilingue/?location=Iztapalapa", salario: "Ver en plataforma" },
  { id: "p1067", tipo: "interprete", modalidad: "presencial", titulo: "Intérprete / Traductora · Iztapalapa · Computrabajo", empresa: "Computrabajo", plataforma: "Computrabajo", ubicacion: "Presencial · Iztapalapa, CDMX", descripcion: "Computrabajo con ubicación en Iztapalapa. Verifica ubicación exacta antes de postularte.", url: "https://mx.computrabajo.com/trabajo-de-interprete-bilingue?l=Iztapalapa", salario: "Ver en plataforma" },
  { id: "p1068", tipo: "interprete", modalidad: "presencial", titulo: "Intérprete / Traductora · Iztapalapa · LinkedIn", empresa: "LinkedIn", plataforma: "LinkedIn", ubicacion: "Presencial · Iztapalapa, CDMX", descripcion: "LinkedIn con ubicación en Iztapalapa, publicadas esta semana. Verifica ubicación antes de postularte.", url: "https://www.linkedin.com/jobs/search/?keywords=interpreter%20bilingual&location=Iztapalapa%2C%20Mexico&f_TPR=r604800", salario: "Ver en plataforma" },
  { id: "p1069", tipo: "interprete", modalidad: "presencial", titulo: "Intérprete / Traductora · Nezahualcóyotl · Indeed", empresa: "Indeed", plataforma: "Indeed", ubicacion: "Presencial · Nezahualcóyotl, EDOMEX", descripcion: "Indeed con ubicación en Nezahualcóyotl. Ordena por fecha para ver las más recientes. Verifica ubicación antes de postularte.", url: "https://www.indeed.com/jobs?q=interprete%20bilingue&l=Nezahualc%C3%B3yotl&sort=date", salario: "Ver en plataforma" },
  { id: "p1070", tipo: "interprete", modalidad: "presencial", titulo: "Intérprete / Traductora · Nezahualcóyotl · OCC", empresa: "OCC Mundial", plataforma: "OCC", ubicacion: "Presencial · Nezahualcóyotl, EDOMEX", descripcion: "OCC con ubicación en Nezahualcóyotl. Confirma que la ubicación sea correcta antes de aplicar.", url: "https://www.occ.com.mx/empleos/de-interprete-bilingue/?location=Nezahualc%C3%B3yotl", salario: "Ver en plataforma" },
  { id: "p1071", tipo: "interprete", modalidad: "presencial", titulo: "Intérprete / Traductora · Nezahualcóyotl · Computrabajo", empresa: "Computrabajo", plataforma: "Computrabajo", ubicacion: "Presencial · Nezahualcóyotl, EDOMEX", descripcion: "Computrabajo con ubicación en Nezahualcóyotl. Verifica ubicación exacta antes de postularte.", url: "https://mx.computrabajo.com/trabajo-de-interprete-bilingue?l=Nezahualc%C3%B3yotl", salario: "Ver en plataforma" },
  { id: "p1072", tipo: "interprete", modalidad: "presencial", titulo: "Intérprete / Traductora · Nezahualcóyotl · LinkedIn", empresa: "LinkedIn", plataforma: "LinkedIn", ubicacion: "Presencial · Nezahualcóyotl, EDOMEX", descripcion: "LinkedIn con ubicación en Nezahualcóyotl, publicadas esta semana. Verifica ubicación antes de postularte.", url: "https://www.linkedin.com/jobs/search/?keywords=interpreter%20bilingual&location=Nezahualc%C3%B3yotl%2C%20Mexico&f_TPR=r604800", salario: "Ver en plataforma" },
  { id: "p1073", tipo: "interprete", modalidad: "presencial", titulo: "Intérprete / Traductora · Los Reyes La Paz · Indeed", empresa: "Indeed", plataforma: "Indeed", ubicacion: "Presencial · Los Reyes La Paz, EDOMEX", descripcion: "Indeed con ubicación en Los Reyes La Paz. Ordena por fecha para ver las más recientes. Verifica ubicación antes de postularte.", url: "https://www.indeed.com/jobs?q=interprete%20bilingue&l=Los%20Reyes%20La%20Paz&sort=date", salario: "Ver en plataforma" },
  { id: "p1074", tipo: "interprete", modalidad: "presencial", titulo: "Intérprete / Traductora · Los Reyes La Paz · OCC", empresa: "OCC Mundial", plataforma: "OCC", ubicacion: "Presencial · Los Reyes La Paz, EDOMEX", descripcion: "OCC con ubicación en Los Reyes La Paz. Confirma que la ubicación sea correcta antes de aplicar.", url: "https://www.occ.com.mx/empleos/de-interprete-bilingue/?location=Los%20Reyes%20La%20Paz", salario: "Ver en plataforma" },
  { id: "p1075", tipo: "interprete", modalidad: "presencial", titulo: "Intérprete / Traductora · Los Reyes La Paz · Computrabajo", empresa: "Computrabajo", plataforma: "Computrabajo", ubicacion: "Presencial · Los Reyes La Paz, EDOMEX", descripcion: "Computrabajo con ubicación en Los Reyes La Paz. Verifica ubicación exacta antes de postularte.", url: "https://mx.computrabajo.com/trabajo-de-interprete-bilingue?l=Los%20Reyes%20La%20Paz", salario: "Ver en plataforma" },
  { id: "p1076", tipo: "interprete", modalidad: "presencial", titulo: "Intérprete / Traductora · Los Reyes La Paz · LinkedIn", empresa: "LinkedIn", plataforma: "LinkedIn", ubicacion: "Presencial · Los Reyes La Paz, EDOMEX", descripcion: "LinkedIn con ubicación en Los Reyes La Paz, publicadas esta semana. Verifica ubicación antes de postularte.", url: "https://www.linkedin.com/jobs/search/?keywords=interpreter%20bilingual&location=Los%20Reyes%20La%20Paz%2C%20Mexico&f_TPR=r604800", salario: "Ver en plataforma" },
  { id: "p1077", tipo: "interprete", modalidad: "presencial", titulo: "Intérprete / Traductora · Texcoco · Indeed", empresa: "Indeed", plataforma: "Indeed", ubicacion: "Presencial · Texcoco, EDOMEX", descripcion: "Indeed con ubicación en Texcoco. Ordena por fecha para ver las más recientes. Verifica ubicación antes de postularte.", url: "https://www.indeed.com/jobs?q=interprete%20bilingue&l=Texcoco&sort=date", salario: "Ver en plataforma" },
  { id: "p1078", tipo: "interprete", modalidad: "presencial", titulo: "Intérprete / Traductora · Texcoco · OCC", empresa: "OCC Mundial", plataforma: "OCC", ubicacion: "Presencial · Texcoco, EDOMEX", descripcion: "OCC con ubicación en Texcoco. Confirma que la ubicación sea correcta antes de aplicar.", url: "https://www.occ.com.mx/empleos/de-interprete-bilingue/?location=Texcoco", salario: "Ver en plataforma" },
  { id: "p1079", tipo: "interprete", modalidad: "presencial", titulo: "Intérprete / Traductora · Texcoco · Computrabajo", empresa: "Computrabajo", plataforma: "Computrabajo", ubicacion: "Presencial · Texcoco, EDOMEX", descripcion: "Computrabajo con ubicación en Texcoco. Verifica ubicación exacta antes de postularte.", url: "https://mx.computrabajo.com/trabajo-de-interprete-bilingue?l=Texcoco", salario: "Ver en plataforma" },
  { id: "p1080", tipo: "interprete", modalidad: "presencial", titulo: "Intérprete / Traductora · Texcoco · LinkedIn", empresa: "LinkedIn", plataforma: "LinkedIn", ubicacion: "Presencial · Texcoco, EDOMEX", descripcion: "LinkedIn con ubicación en Texcoco, publicadas esta semana. Verifica ubicación antes de postularte.", url: "https://www.linkedin.com/jobs/search/?keywords=interpreter%20bilingual&location=Texcoco%2C%20Mexico&f_TPR=r604800", salario: "Ver en plataforma" },
  { id: "p1081", tipo: "interprete", modalidad: "presencial", titulo: "Intérprete / Traductora · Chimalhuacán · Indeed", empresa: "Indeed", plataforma: "Indeed", ubicacion: "Presencial · Chimalhuacán, EDOMEX", descripcion: "Indeed con ubicación en Chimalhuacán. Ordena por fecha para ver las más recientes. Verifica ubicación antes de postularte.", url: "https://www.indeed.com/jobs?q=interprete%20bilingue&l=Chimalhuac%C3%A1n&sort=date", salario: "Ver en plataforma" },
  { id: "p1082", tipo: "interprete", modalidad: "presencial", titulo: "Intérprete / Traductora · Chimalhuacán · OCC", empresa: "OCC Mundial", plataforma: "OCC", ubicacion: "Presencial · Chimalhuacán, EDOMEX", descripcion: "OCC con ubicación en Chimalhuacán. Confirma que la ubicación sea correcta antes de aplicar.", url: "https://www.occ.com.mx/empleos/de-interprete-bilingue/?location=Chimalhuac%C3%A1n", salario: "Ver en plataforma" },
  { id: "p1083", tipo: "interprete", modalidad: "presencial", titulo: "Intérprete / Traductora · Chimalhuacán · Computrabajo", empresa: "Computrabajo", plataforma: "Computrabajo", ubicacion: "Presencial · Chimalhuacán, EDOMEX", descripcion: "Computrabajo con ubicación en Chimalhuacán. Verifica ubicación exacta antes de postularte.", url: "https://mx.computrabajo.com/trabajo-de-interprete-bilingue?l=Chimalhuac%C3%A1n", salario: "Ver en plataforma" },
  { id: "p1084", tipo: "interprete", modalidad: "presencial", titulo: "Intérprete / Traductora · Chimalhuacán · LinkedIn", empresa: "LinkedIn", plataforma: "LinkedIn", ubicacion: "Presencial · Chimalhuacán, EDOMEX", descripcion: "LinkedIn con ubicación en Chimalhuacán, publicadas esta semana. Verifica ubicación antes de postularte.", url: "https://www.linkedin.com/jobs/search/?keywords=interpreter%20bilingual&location=Chimalhuac%C3%A1n%2C%20Mexico&f_TPR=r604800", salario: "Ver en plataforma" },
  { id: "p1085", tipo: "atencion", modalidad: "presencial", titulo: "Atención Clientes · Iztapalapa · Indeed", empresa: "Indeed", plataforma: "Indeed", ubicacion: "Presencial · Iztapalapa, CDMX", descripcion: "Indeed con ubicación en Iztapalapa. Ordena por fecha para ver las más recientes. Verifica ubicación antes de postularte.", url: "https://www.indeed.com/jobs?q=ejecutivo%20bilingue%20ingles&l=Iztapalapa&sort=date", salario: "Ver en plataforma" },
  { id: "p1086", tipo: "atencion", modalidad: "presencial", titulo: "Atención Clientes · Iztapalapa · OCC", empresa: "OCC Mundial", plataforma: "OCC", ubicacion: "Presencial · Iztapalapa, CDMX", descripcion: "OCC con ubicación en Iztapalapa. Confirma que la ubicación sea correcta antes de aplicar.", url: "https://www.occ.com.mx/empleos/de-atencion-a-clientes-bilingue/?location=Iztapalapa", salario: "Ver en plataforma" },
  { id: "p1087", tipo: "atencion", modalidad: "presencial", titulo: "Atención Clientes · Iztapalapa · Computrabajo", empresa: "Computrabajo", plataforma: "Computrabajo", ubicacion: "Presencial · Iztapalapa, CDMX", descripcion: "Computrabajo con ubicación en Iztapalapa. Verifica ubicación exacta antes de postularte.", url: "https://mx.computrabajo.com/trabajo-de-ejecutivo-bilingue?l=Iztapalapa", salario: "Ver en plataforma" },
  { id: "p1088", tipo: "atencion", modalidad: "presencial", titulo: "Atención Clientes · Iztapalapa · LinkedIn", empresa: "LinkedIn", plataforma: "LinkedIn", ubicacion: "Presencial · Iztapalapa, CDMX", descripcion: "LinkedIn con ubicación en Iztapalapa, publicadas esta semana. Verifica ubicación antes de postularte.", url: "https://www.linkedin.com/jobs/search/?keywords=bilingual%20customer%20service&location=Iztapalapa%2C%20Mexico&f_TPR=r604800", salario: "Ver en plataforma" },
  { id: "p1089", tipo: "atencion", modalidad: "presencial", titulo: "Atención Clientes · Nezahualcóyotl · Indeed", empresa: "Indeed", plataforma: "Indeed", ubicacion: "Presencial · Nezahualcóyotl, EDOMEX", descripcion: "Indeed con ubicación en Nezahualcóyotl. Ordena por fecha para ver las más recientes. Verifica ubicación antes de postularte.", url: "https://www.indeed.com/jobs?q=ejecutivo%20bilingue%20ingles&l=Nezahualc%C3%B3yotl&sort=date", salario: "Ver en plataforma" },
  { id: "p1090", tipo: "atencion", modalidad: "presencial", titulo: "Atención Clientes · Nezahualcóyotl · OCC", empresa: "OCC Mundial", plataforma: "OCC", ubicacion: "Presencial · Nezahualcóyotl, EDOMEX", descripcion: "OCC con ubicación en Nezahualcóyotl. Confirma que la ubicación sea correcta antes de aplicar.", url: "https://www.occ.com.mx/empleos/de-atencion-a-clientes-bilingue/?location=Nezahualc%C3%B3yotl", salario: "Ver en plataforma" },
  { id: "p1091", tipo: "atencion", modalidad: "presencial", titulo: "Atención Clientes · Nezahualcóyotl · Computrabajo", empresa: "Computrabajo", plataforma: "Computrabajo", ubicacion: "Presencial · Nezahualcóyotl, EDOMEX", descripcion: "Computrabajo con ubicación en Nezahualcóyotl. Verifica ubicación exacta antes de postularte.", url: "https://mx.computrabajo.com/trabajo-de-ejecutivo-bilingue?l=Nezahualc%C3%B3yotl", salario: "Ver en plataforma" },
  { id: "p1092", tipo: "atencion", modalidad: "presencial", titulo: "Atención Clientes · Nezahualcóyotl · LinkedIn", empresa: "LinkedIn", plataforma: "LinkedIn", ubicacion: "Presencial · Nezahualcóyotl, EDOMEX", descripcion: "LinkedIn con ubicación en Nezahualcóyotl, publicadas esta semana. Verifica ubicación antes de postularte.", url: "https://www.linkedin.com/jobs/search/?keywords=bilingual%20customer%20service&location=Nezahualc%C3%B3yotl%2C%20Mexico&f_TPR=r604800", salario: "Ver en plataforma" },
  { id: "p1093", tipo: "atencion", modalidad: "presencial", titulo: "Atención Clientes · Los Reyes La Paz · Indeed", empresa: "Indeed", plataforma: "Indeed", ubicacion: "Presencial · Los Reyes La Paz, EDOMEX", descripcion: "Indeed con ubicación en Los Reyes La Paz. Ordena por fecha para ver las más recientes. Verifica ubicación antes de postularte.", url: "https://www.indeed.com/jobs?q=ejecutivo%20bilingue%20ingles&l=Los%20Reyes%20La%20Paz&sort=date", salario: "Ver en plataforma" },
  { id: "p1094", tipo: "atencion", modalidad: "presencial", titulo: "Atención Clientes · Los Reyes La Paz · OCC", empresa: "OCC Mundial", plataforma: "OCC", ubicacion: "Presencial · Los Reyes La Paz, EDOMEX", descripcion: "OCC con ubicación en Los Reyes La Paz. Confirma que la ubicación sea correcta antes de aplicar.", url: "https://www.occ.com.mx/empleos/de-atencion-a-clientes-bilingue/?location=Los%20Reyes%20La%20Paz", salario: "Ver en plataforma" },
  { id: "p1095", tipo: "atencion", modalidad: "presencial", titulo: "Atención Clientes · Los Reyes La Paz · Computrabajo", empresa: "Computrabajo", plataforma: "Computrabajo", ubicacion: "Presencial · Los Reyes La Paz, EDOMEX", descripcion: "Computrabajo con ubicación en Los Reyes La Paz. Verifica ubicación exacta antes de postularte.", url: "https://mx.computrabajo.com/trabajo-de-ejecutivo-bilingue?l=Los%20Reyes%20La%20Paz", salario: "Ver en plataforma" },
  { id: "p1096", tipo: "atencion", modalidad: "presencial", titulo: "Atención Clientes · Los Reyes La Paz · LinkedIn", empresa: "LinkedIn", plataforma: "LinkedIn", ubicacion: "Presencial · Los Reyes La Paz, EDOMEX", descripcion: "LinkedIn con ubicación en Los Reyes La Paz, publicadas esta semana. Verifica ubicación antes de postularte.", url: "https://www.linkedin.com/jobs/search/?keywords=bilingual%20customer%20service&location=Los%20Reyes%20La%20Paz%2C%20Mexico&f_TPR=r604800", salario: "Ver en plataforma" },
  { id: "p1097", tipo: "atencion", modalidad: "presencial", titulo: "Atención Clientes · Texcoco · Indeed", empresa: "Indeed", plataforma: "Indeed", ubicacion: "Presencial · Texcoco, EDOMEX", descripcion: "Indeed con ubicación en Texcoco. Ordena por fecha para ver las más recientes. Verifica ubicación antes de postularte.", url: "https://www.indeed.com/jobs?q=ejecutivo%20bilingue%20ingles&l=Texcoco&sort=date", salario: "Ver en plataforma" },
  { id: "p1098", tipo: "atencion", modalidad: "presencial", titulo: "Atención Clientes · Texcoco · OCC", empresa: "OCC Mundial", plataforma: "OCC", ubicacion: "Presencial · Texcoco, EDOMEX", descripcion: "OCC con ubicación en Texcoco. Confirma que la ubicación sea correcta antes de aplicar.", url: "https://www.occ.com.mx/empleos/de-atencion-a-clientes-bilingue/?location=Texcoco", salario: "Ver en plataforma" },
  { id: "p1099", tipo: "atencion", modalidad: "presencial", titulo: "Atención Clientes · Texcoco · Computrabajo", empresa: "Computrabajo", plataforma: "Computrabajo", ubicacion: "Presencial · Texcoco, EDOMEX", descripcion: "Computrabajo con ubicación en Texcoco. Verifica ubicación exacta antes de postularte.", url: "https://mx.computrabajo.com/trabajo-de-ejecutivo-bilingue?l=Texcoco", salario: "Ver en plataforma" },
  { id: "p1100", tipo: "atencion", modalidad: "presencial", titulo: "Atención Clientes · Texcoco · LinkedIn", empresa: "LinkedIn", plataforma: "LinkedIn", ubicacion: "Presencial · Texcoco, EDOMEX", descripcion: "LinkedIn con ubicación en Texcoco, publicadas esta semana. Verifica ubicación antes de postularte.", url: "https://www.linkedin.com/jobs/search/?keywords=bilingual%20customer%20service&location=Texcoco%2C%20Mexico&f_TPR=r604800", salario: "Ver en plataforma" },
  { id: "p1101", tipo: "atencion", modalidad: "presencial", titulo: "Atención Clientes · Chimalhuacán · Indeed", empresa: "Indeed", plataforma: "Indeed", ubicacion: "Presencial · Chimalhuacán, EDOMEX", descripcion: "Indeed con ubicación en Chimalhuacán. Ordena por fecha para ver las más recientes. Verifica ubicación antes de postularte.", url: "https://www.indeed.com/jobs?q=ejecutivo%20bilingue%20ingles&l=Chimalhuac%C3%A1n&sort=date", salario: "Ver en plataforma" },
  { id: "p1102", tipo: "atencion", modalidad: "presencial", titulo: "Atención Clientes · Chimalhuacán · OCC", empresa: "OCC Mundial", plataforma: "OCC", ubicacion: "Presencial · Chimalhuacán, EDOMEX", descripcion: "OCC con ubicación en Chimalhuacán. Confirma que la ubicación sea correcta antes de aplicar.", url: "https://www.occ.com.mx/empleos/de-atencion-a-clientes-bilingue/?location=Chimalhuac%C3%A1n", salario: "Ver en plataforma" },
  { id: "p1103", tipo: "atencion", modalidad: "presencial", titulo: "Atención Clientes · Chimalhuacán · Computrabajo", empresa: "Computrabajo", plataforma: "Computrabajo", ubicacion: "Presencial · Chimalhuacán, EDOMEX", descripcion: "Computrabajo con ubicación en Chimalhuacán. Verifica ubicación exacta antes de postularte.", url: "https://mx.computrabajo.com/trabajo-de-ejecutivo-bilingue?l=Chimalhuac%C3%A1n", salario: "Ver en plataforma" },
  { id: "p1104", tipo: "atencion", modalidad: "presencial", titulo: "Atención Clientes · Chimalhuacán · LinkedIn", empresa: "LinkedIn", plataforma: "LinkedIn", ubicacion: "Presencial · Chimalhuacán, EDOMEX", descripcion: "LinkedIn con ubicación en Chimalhuacán, publicadas esta semana. Verifica ubicación antes de postularte.", url: "https://www.linkedin.com/jobs/search/?keywords=bilingual%20customer%20service&location=Chimalhuac%C3%A1n%2C%20Mexico&f_TPR=r604800", salario: "Ver en plataforma" }
];

const VACANTES_REMOTO = [
  { id: "r1", tipo: "paralegal", modalidad: "remoto", titulo: "Paralegal Inmigración Bilingüe · LinkedIn", empresa: "LinkedIn", plataforma: "LinkedIn", ubicacion: "Remoto · Worldwide", descripcion: "Firmas EE.UU. buscan paralegal bilingüe. Filtra Remote y Most Recent para ver las más nuevas.", url: "https://www.linkedin.com/jobs/search/?keywords=paralegal%20immigration%20bilingual%20spanish&f_WT=2&sortBy=DD", salario: "$45,000-65,000/año" },
  { id: "r2", tipo: "paralegal", modalidad: "remoto", titulo: "Legal Assistant Immigration · Indeed", empresa: "Indeed", plataforma: "Indeed", ubicacion: "Remoto · USA", descripcion: "Filtro Remote activo. Ordena Last 7 days para ver las más recientes.", url: "https://www.indeed.com/jobs?q=legal%20assistant%20immigration%20bilingual%20spanish&sc=0kf%3Aattr(DSQF7)%3B&sort=date", salario: "$18-28/hr" },
  { id: "r3", tipo: "paralegal", modalidad: "remoto", titulo: "Paralegal Removal Defense / Asylum · Indeed", empresa: "Indeed", plataforma: "Indeed", ubicacion: "Remoto · USA", descripcion: "Búsqueda específica removal defense y asylum con filtro remoto.", url: "https://www.indeed.com/jobs?q=paralegal%20removal%20defense%20asylum%20bilingual&sc=0kf%3Aattr(DSQF7)%3B&sort=date", salario: "$20-30/hr" },
  { id: "r4", tipo: "paralegal", modalidad: "remoto", titulo: "Immigration Paralegal · ZipRecruiter", empresa: "ZipRecruiter", plataforma: "ZipRecruiter", ubicacion: "Remoto · USA", descripcion: "Miles de firmas de inmigración EE.UU. buscando paralegal bilingüe remoto.", url: "https://www.ziprecruiter.com/Jobs/Immigration-Paralegal-Bilingual-Spanish-Remote", salario: "$45,000-65,000/año" },
  { id: "r5", tipo: "paralegal", modalidad: "remoto", titulo: "Paralegal IP Propiedad Intelectual · LinkedIn", empresa: "LinkedIn", plataforma: "LinkedIn", ubicacion: "Remoto · Worldwide", descripcion: "Firmas internacionales de IP buscan paralegal bilingüe con experiencia en patentes.", url: "https://www.linkedin.com/jobs/search/?keywords=paralegal%20intellectual%20property%20bilingual%20spanish&f_WT=2&sortBy=DD", salario: "$50,000-70,000/año" },
  { id: "r6", tipo: "paralegal", modalidad: "remoto", titulo: "Patent Paralegal Bilingual · Indeed", empresa: "Indeed", plataforma: "Indeed", ubicacion: "Remoto · USA", descripcion: "Paralegal en propiedad intelectual, patentes y marcas. Filtro Remote activo.", url: "https://www.indeed.com/jobs?q=IP%20paralegal%20intellectual%20property%20bilingual&sc=0kf%3Aattr(DSQF7)%3B&sort=date", salario: "$50,000-70,000/año" },
  { id: "r7", tipo: "paralegal", modalidad: "remoto", titulo: "Legal Jobs Remote · RemoteOK", empresa: "RemoteOK", plataforma: "RemoteOK", ubicacion: "Remoto · Worldwide", descripcion: "Portal 100% remoto. Sección legal actualizada diariamente.", url: "https://remoteok.com/remote-legal-jobs", salario: "Ver en plataforma" },
  { id: "r8", tipo: "paralegal", modalidad: "remoto", titulo: "Legal Positions · WeWorkRemotely", empresa: "WeWorkRemotely", plataforma: "WeWorkRemotely", ubicacion: "Remoto · Worldwide", descripcion: "Bolsa remota top. Sección Legal con vacantes internacionales.", url: "https://weworkremotely.com/remote-jobs/search?term=paralegal+bilingual+legal", salario: "Ver en plataforma" },
  { id: "r9", tipo: "paralegal", modalidad: "remoto", titulo: "Legal Paralegal Freelance · Upwork", empresa: "Upwork", plataforma: "Upwork", ubicacion: "Remoto · Worldwide", descripcion: "Plataforma freelance líder. Proyectos immigration law y IP para clientes EE.UU.", url: "https://www.upwork.com/search/jobs/?q=paralegal+immigration+bilingual+spanish&sort=recency", salario: "$25-50/hr" },
  { id: "r10", tipo: "paralegal", modalidad: "remoto", titulo: "Legal Freelance LATAM · Workana", empresa: "Workana", plataforma: "Workana", ubicacion: "Remoto · LATAM", descripcion: "Mayor plataforma freelance LATAM. Proyectos legales y traducción.", url: "https://www.workana.com/jobs?category=legal-law", salario: "Por proyecto" },
  { id: "r11", tipo: "paralegal", modalidad: "remoto", titulo: "Paralegal Home Office · OCC", empresa: "OCC Mundial", plataforma: "OCC", ubicacion: "Remoto · México", descripcion: "Bolsa líder México. Paralegal y asistente legal en Home Office.", url: "https://www.occ.com.mx/empleos/de-paralegal/?modality=3", salario: "Ver en plataforma" },
  { id: "r12", tipo: "paralegal", modalidad: "remoto", titulo: "Paralegal Teletrabajo · Computrabajo", empresa: "Computrabajo", plataforma: "Computrabajo", ubicacion: "Remoto · México", descripcion: "Computrabajo filtrando teletrabajo para paralegal y asistente legal bilingüe.", url: "https://mx.computrabajo.com/trabajo-de-paralegal-bilingue?jt=4", salario: "Ver en plataforma" },
  { id: "r13", tipo: "paralegal", modalidad: "remoto", titulo: "Paralegal Bilingüe Remote · Google Jobs", empresa: "Google Jobs", plataforma: "Google Jobs", ubicacion: "Remoto · México / USA", descripcion: "Google agrega vacantes de todas las bolsas con filtro remoto activado.", url: "https://www.google.com/search?q=paralegal+bilingue+remoto&ibp=htl;jobs&htichips=employment_type:TELECOMMUTE,date_posted:week", salario: "Ver en plataforma" },
  { id: "r14", tipo: "paralegal", modalidad: "remoto", titulo: "Paralegal EE.UU. Remote · Google Jobs", empresa: "Google Jobs", plataforma: "Google Jobs", ubicacion: "Remoto · USA", descripcion: "Firmas de inmigración EE.UU. buscando paralegal bilingüe remoto.", url: "https://www.google.com/search?q=paralegal+immigration+bilingual+remote&ibp=htl;jobs&htichips=employment_type:TELECOMMUTE,date_posted:week", salario: "Ver en plataforma" },
  { id: "r15", tipo: "paralegal", modalidad: "remoto", titulo: "Propiedad Intelectual Remote · Google Jobs", empresa: "Google Jobs", plataforma: "Google Jobs", ubicacion: "Remoto · Worldwide", descripcion: "Vacantes remotas de propiedad intelectual y patentes para perfil bilingüe.", url: "https://www.google.com/search?q=paralegal+propiedad+intelectual+remoto&ibp=htl;jobs&htichips=employment_type:TELECOMMUTE,date_posted:week", salario: "Ver en plataforma" },
  { id: "r20", tipo: "asistente", modalidad: "remoto", titulo: "Virtual Assistant Bilingüe · LinkedIn", empresa: "LinkedIn", plataforma: "LinkedIn", ubicacion: "Remoto · USA / LATAM", descripcion: "Asistente virtual bilingüe para firmas y empresas EE.UU. 100% remoto desde México.", url: "https://www.linkedin.com/jobs/search/?keywords=virtual%20assistant%20bilingual%20spanish%20english&f_WT=2&sortBy=DD", salario: "$15-25/hr" },
  { id: "r21", tipo: "asistente", modalidad: "remoto", titulo: "Administrative Assistant Bilingüe · Indeed", empresa: "Indeed", plataforma: "Indeed", ubicacion: "Remoto · USA", descripcion: "Asistentes administrativas bilingüe para empresas EE.UU. Filtro Remote activo.", url: "https://www.indeed.com/jobs?q=administrative%20assistant%20bilingual%20spanish&sc=0kf%3Aattr(DSQF7)%3B&sort=date", salario: "$16-22/hr" },
  { id: "r22", tipo: "asistente", modalidad: "remoto", titulo: "Executive Assistant Bilingüe · Glassdoor", empresa: "Glassdoor", plataforma: "Glassdoor", ubicacion: "Remoto · USA", descripcion: "Asistentes ejecutivas bilingüe para directivos de empresas internacionales.", url: "https://www.glassdoor.com/Job/jobs.htm?sc.keyword=executive+assistant+bilingual+spanish+remote&remoteWorkType=1&sortBy=date_desc", salario: "$45,000-65,000/año" },
  { id: "r23", tipo: "asistente", modalidad: "remoto", titulo: "Operations Coordinator Bilingüe · ZipRecruiter", empresa: "ZipRecruiter", plataforma: "ZipRecruiter", ubicacion: "Remoto · USA", descripcion: "Coordinadoras de operaciones bilingüe para empresas con equipos en LATAM.", url: "https://www.ziprecruiter.com/Jobs/Operations-Coordinator-Bilingual-Spanish-Remote", salario: "$45,000-60,000/año" },
  { id: "r24", tipo: "asistente", modalidad: "remoto", titulo: "Asistente Bilingüe Home Office · OCC", empresa: "OCC Mundial", plataforma: "OCC", ubicacion: "Remoto · México", descripcion: "Bolsa líder México. Asistente bilingüe en Home Office. Solo resultados remotos.", url: "https://www.occ.com.mx/empleos/de-asistente-bilingue/?modality=3", salario: "Ver en plataforma" },
  { id: "r25", tipo: "asistente", modalidad: "remoto", titulo: "Asistente Bilingüe Teletrabajo · Computrabajo", empresa: "Computrabajo", plataforma: "Computrabajo", ubicacion: "Remoto · México", descripcion: "Asistente bilingüe en teletrabajo. Solo resultados remotos.", url: "https://mx.computrabajo.com/trabajo-de-asistente-bilingue?jt=4", salario: "Ver en plataforma" },
  { id: "r26", tipo: "asistente", modalidad: "remoto", titulo: "Bilingual Coordinator · Hireline", empresa: "Hireline", plataforma: "Hireline", ubicacion: "Remoto · LATAM", descripcion: "Plataforma LATAM especializada en trabajo 100% remoto con empresas que pagan en USD.", url: "https://hireline.io/mx/empleos-remotos?q=bilingue+asistente", salario: "USD" },
  { id: "r27", tipo: "asistente", modalidad: "remoto", titulo: "Asistente Bilingüe Remote · Google Jobs", empresa: "Google Jobs", plataforma: "Google Jobs", ubicacion: "Remoto · México / USA", descripcion: "Google agrega vacantes de todas las bolsas con filtro remoto.", url: "https://www.google.com/search?q=asistente+bilingue+home+office&ibp=htl;jobs&htichips=employment_type:TELECOMMUTE,date_posted:week", salario: "Ver en plataforma" },
  { id: "r30", tipo: "teacher", modalidad: "remoto", titulo: "Online English Teacher · LinkedIn", empresa: "LinkedIn", plataforma: "LinkedIn", ubicacion: "Remoto · Worldwide", descripcion: "Plataformas de inglés online buscan maestras bilingüe. TOEIC 920 es diferenciador.", url: "https://www.linkedin.com/jobs/search/?keywords=online%20english%20teacher%20bilingual%20remote&f_WT=2&sortBy=DD", salario: "$15-30/hr" },
  { id: "r31", tipo: "teacher", modalidad: "remoto", titulo: "English Tutor / Teacher Online · Indeed", empresa: "Indeed", plataforma: "Indeed", ubicacion: "Remoto · Worldwide", descripcion: "Tutor de inglés online para adultos y corporativos. Filtro Remote activo.", url: "https://www.indeed.com/jobs?q=english%20teacher%20tutor%20online%20bilingual%20spanish&sc=0kf%3Aattr(DSQF7)%3B&sort=date", salario: "$15-25/hr" },
  { id: "r32", tipo: "teacher", modalidad: "remoto", titulo: "ESL Teacher Online · RemoteOK", empresa: "RemoteOK", plataforma: "RemoteOK", ubicacion: "Remoto · Worldwide", descripcion: "Plataformas ESL buscan maestras bilingüe. Portal 100% remoto.", url: "https://remoteok.com/remote-teacher-jobs", salario: "$15-28/hr" },
  { id: "r33", tipo: "teacher", modalidad: "remoto", titulo: "English Teacher Home Office · OCC", empresa: "OCC Mundial", plataforma: "OCC", ubicacion: "Remoto · México", descripcion: "Maestras de inglés en modalidad Home Office en México.", url: "https://www.occ.com.mx/empleos/de-maestro-ingles/?modality=3", salario: "Ver en plataforma" },
  { id: "r34", tipo: "teacher", modalidad: "remoto", titulo: "English Teacher Teletrabajo · Computrabajo", empresa: "Computrabajo", plataforma: "Computrabajo", ubicacion: "Remoto · México", descripcion: "Maestras de inglés en teletrabajo. Solo resultados remotos.", url: "https://mx.computrabajo.com/trabajo-de-maestro-ingles?jt=4", salario: "Ver en plataforma" },
  { id: "r35", tipo: "teacher", modalidad: "remoto", titulo: "English Teacher Online · Google Jobs", empresa: "Google Jobs", plataforma: "Google Jobs", ubicacion: "Remoto · México", descripcion: "Google Jobs con filtro remoto para maestras de inglés online.", url: "https://www.google.com/search?q=maestra+ingles+online+remoto&ibp=htl;jobs&htichips=employment_type:TELECOMMUTE,date_posted:week", salario: "Ver en plataforma" },
  { id: "r40", tipo: "interprete", modalidad: "remoto", titulo: "Legal Translator Spanish-English · LinkedIn", empresa: "LinkedIn", plataforma: "LinkedIn", ubicacion: "Remoto · Worldwide", descripcion: "Traductoras legales español-inglés para firmas y organismos internacionales.", url: "https://www.linkedin.com/jobs/search/?keywords=legal%20translator%20spanish%20english%20remote&f_WT=2&sortBy=DD", salario: "$25-50/hr" },
  { id: "r41", tipo: "interprete", modalidad: "remoto", titulo: "Legal Translation · Upwork", empresa: "Upwork", plataforma: "Upwork", ubicacion: "Remoto · Worldwide", descripcion: "Proyectos de traducción legal español-inglés para clientes EE.UU.", url: "https://www.upwork.com/search/jobs/?q=legal+translation+spanish+english&sort=recency", salario: "$25-60/hr" },
  { id: "r42", tipo: "interprete", modalidad: "remoto", titulo: "Remote Interpreter Bilingual · Indeed", empresa: "Indeed", plataforma: "Indeed", ubicacion: "Remoto · USA", descripcion: "Intérpretes bilingüe para sesiones legales vía videollamada. Filtro Remote activo.", url: "https://www.indeed.com/jobs?q=interpreter%20bilingual%20spanish%20english%20remote&sc=0kf%3Aattr(DSQF7)%3B&sort=date", salario: "$18-35/hr" },
  { id: "r43", tipo: "interprete", modalidad: "remoto", titulo: "Intérprete Home Office · OCC", empresa: "OCC Mundial", plataforma: "OCC", ubicacion: "Remoto · México", descripcion: "Intérprete bilingüe en Home Office México.", url: "https://www.occ.com.mx/empleos/de-interprete-bilingue/?modality=3", salario: "Ver en plataforma" },
  { id: "r44", tipo: "interprete", modalidad: "remoto", titulo: "Traductora Teletrabajo · Computrabajo", empresa: "Computrabajo", plataforma: "Computrabajo", ubicacion: "Remoto · México", descripcion: "Traductoras e intérpretes bilingüe en teletrabajo.", url: "https://mx.computrabajo.com/trabajo-de-interprete-bilingue?jt=4", salario: "Ver en plataforma" },
  { id: "r45", tipo: "interprete", modalidad: "remoto", titulo: "Intérprete Bilingüe Remote · Google Jobs", empresa: "Google Jobs", plataforma: "Google Jobs", ubicacion: "Remoto · México / USA", descripcion: "Google Jobs con filtro remoto para intérpretes y traductores bilingüe.", url: "https://www.google.com/search?q=interprete+traductor+bilingue+remoto&ibp=htl;jobs&htichips=employment_type:TELECOMMUTE,date_posted:week", salario: "Ver en plataforma" },
  { id: "r50", tipo: "atencion", modalidad: "remoto", titulo: "Customer Success Bilingüe · LinkedIn", empresa: "LinkedIn", plataforma: "LinkedIn", ubicacion: "Remoto · USA / LATAM", descripcion: "Empresas EE.UU. buscan customer success bilingüe. Paga en USD, 100% remoto.", url: "https://www.linkedin.com/jobs/search/?keywords=customer%20success%20bilingual%20spanish%20english%20remote&f_WT=2&sortBy=DD", salario: "$40,000-60,000/año" },
  { id: "r51", tipo: "atencion", modalidad: "remoto", titulo: "Client Services Coordinator Bilingüe · Indeed", empresa: "Indeed", plataforma: "Indeed", ubicacion: "Remoto · USA", descripcion: "Coordinadoras de servicio al cliente bilingüe para firmas EE.UU. Filtro Remote.", url: "https://www.indeed.com/jobs?q=client%20services%20coordinator%20bilingual%20spanish&sc=0kf%3Aattr(DSQF7)%3B&sort=date", salario: "$18-25/hr" },
  { id: "r52", tipo: "atencion", modalidad: "remoto", titulo: "Bilingual Customer Support · ZipRecruiter", empresa: "ZipRecruiter", plataforma: "ZipRecruiter", ubicacion: "Remoto · USA", descripcion: "Soporte al cliente bilingüe para empresas EE.UU. en español e inglés.", url: "https://www.ziprecruiter.com/Jobs/Bilingual-Customer-Support-Spanish-English-Remote", salario: "$16-22/hr" },
  { id: "r53", tipo: "atencion", modalidad: "remoto", titulo: "Atención Clientes Home Office · OCC", empresa: "OCC Mundial", plataforma: "OCC", ubicacion: "Remoto · México", descripcion: "Atención a clientes bilingüe en Home Office México. Solo resultados remotos.", url: "https://www.occ.com.mx/empleos/de-atencion-a-clientes-bilingue/?modality=3", salario: "Ver en plataforma" },
  { id: "r54", tipo: "atencion", modalidad: "remoto", titulo: "Ejecutivo Bilingüe Teletrabajo · Computrabajo", empresa: "Computrabajo", plataforma: "Computrabajo", ubicacion: "Remoto · México", descripcion: "Ejecutivos bilingüe en atención a clientes modalidad teletrabajo.", url: "https://mx.computrabajo.com/trabajo-de-ejecutivo-bilingue?jt=4", salario: "Ver en plataforma" },
  { id: "r55", tipo: "atencion", modalidad: "remoto", titulo: "Atención Clientes Remote · Google Jobs", empresa: "Google Jobs", plataforma: "Google Jobs", ubicacion: "Remoto · México / USA", descripcion: "Google Jobs filtrando atención a clientes bilingüe remota. Vacantes actualizadas.", url: "https://www.google.com/search?q=atencion+clientes+bilingue+home+office&ibp=htl;jobs&htichips=employment_type:TELECOMMUTE,date_posted:week", salario: "Ver en plataforma" }
];

const VACANTES = [...VACANTES_REMOTO, ...PRESENCIALES];

export default async function handler(req, res) {
  const { method } = req;

  if (method === "GET") {
    const favoritos = await redis.get("favoritos") || [];
    return res.status(200).json({ favoritos });
  }

  if (method === "POST") {
    const { action, data } = req.body;

    if (action === "search") {
      const { tipo, modalidad } = data;
      const tc = await getUSDtoMXN();
      let vacantes = VACANTES;
      if (tipo && tipo !== "todos") vacantes = vacantes.filter(v => v.tipo === tipo);
      if (modalidad && modalidad !== "todos") vacantes = vacantes.filter(v => v.modalidad === modalidad);
      const resultado = vacantes.map(v => ({ ...v, salarioMXN: convertirSalario(v.salario, tc) }));
      return res.status(200).json({ vacantes: resultado, tipoCambio: tc });
    }

    if (action === "toggle_favorito") {
      const { id } = data;
      let favoritos = await redis.get("favoritos") || [];
      favoritos = favoritos.includes(id) ? favoritos.filter(f => f !== id) : [...favoritos, id];
      await redis.set("favoritos", favoritos);
      return res.status(200).json({ favoritos });
    }
  }

  res.status(405).json({ error: "Method not allowed" });
}
